site:
  name: "Infinite Vault"
  description: "Riassunti, personaggi e luoghi di Infinite Jest"
  nav:
    - title: "🏠 Home"
      url: /
    - title: "📘 Riassunti"
      url: /riassunti/
    - title: "🧍 Personaggi"
      url: /personaggi/
    - title: "📍 Luoghi"
      url: /luoghi/

theme:
  appearance: "light"   # puoi mettere anche "dark" o "auto"
  accentColor: "indigo" # colori supportati: blue, green, pink, orange, etc.

favicon: "/static/favicon.ico"

markdown:
  smartquotes: true
